
export const memberActivities = [
  {
    id: 1,
    fullname: "Jane Doe",
    email: "jane.doe@example.com",
    role: "Admin",
    item: "Handbag",
    img: '/Images/activitiesImage.jpg',
    timestamp: "2 mins ago",
    action: "Deleted listing",
  },
  {
    id: 2,
    fullname: "Michael Smith",
    email: "michael.smith@example.com",
    role: "Organizer",
    item: "Travel Suitcase",
    img: '/Images/activitiesImage.jpg',
    timestamp: "1 hour ago",
    action: "Saved listing",
  },
  {
    id: 3,
    fullname: "Sarah Johnson",
    email: "sarah.johnson@example.com",
    role: "Editor",
    item: "Fragrancex",
    img: "/Images/Fx.png",
    timestamp: "3 hours ago",
    action: "Enroled vendor",
  },
  {
    id: 4,
    fullname: "David Brown",
    email: "david.brown@example.com",
    role: "Admin",
    item: "Fragrancex",
    timestamp: "Yesterday",
    action: "Deleted vendor",
  },
  {
    id: 5,
    fullname: "Emily Davis",
    email: "emily.davis@example.com",
    role: "Organizer",
    item: "Handbag",
    img: '../Images/activitiesImage.jpg',
    timestamp: "5 mins ago",
    action: "Saved listing",
  },
  {
    id: 6,
    fullname: "John Wilson",
    email: "john.wilson@example.com",
    role: "Editor",
    item: "Travel Suitcase",
    timestamp: "30 mins ago",
    action: "Deleted listing",
  },
  {
    id: 7,
    fullname: "Sophia Taylor",
    email: "sophia.taylor@example.com",
    role: "Admin",
    item: "Fragrancex",
    timestamp: "2 hours ago",
    action: "Enroled vendor",
  },
  {
    id: 8,
    fullname: "Daniel Martinez",
    email: "daniel.martinez@example.com",
    role: "Editor",
    item: "Fragrancex",
    img: "/images/Fx.png",
    timestamp: "Today",
    action: "Saved listing",
  },
  {
    id: 9,
    fullname: "Olivia Garcia",
    email: "olivia.garcia@example.com",
    role: "Organizer",
    item: "Handbag",
    img: "/images/activitiesImage.jpg",
    timestamp: "10 mins ago",
    action: "Deleted vendor",
  },
  {
    id: 10,
    fullname: "Liam Anderson",
    email: "liam.anderson@example.com",
    role: "Admin",
    item: "Travel Suitcase",
    img: '../Images/activitiesImage.jpg',
    timestamp: "3 days ago",
    action: "Deleted listing",
  },
];
